version: 2
registries:
  npm-registry-npm-pkg-github-com-platformbuilders:
    type: npm-registry
    url: https://npm.pkg.github.com/platformbuilders
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_PLATFORMBUILDERS_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Brazil/East
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.9
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.46
    - 0.63.48
    - 0.63.49
    - 0.63.50
    - 0.63.51
    - 0.64.0
    - 0.64.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  registries:
  - npm-registry-npm-pkg-github-com-platformbuilders
